name: Build and Test Application

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the pipeline on the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up the .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'  

      # Step 3: Restore NuGet dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Step 4: Build the application
      - name: Build Application
        run: dotnet build --configuration Release

      # Step 5: Run unit tests
      - name: Run Unit Tests
        run: dotnet test --configuration Release --verbosity normal
